json.id @notification_setting.id
json.user_id @notification_setting.user_id
json.account_id @notification_setting.account_id
json.all_email_flags NotificationSetting::VISIBLE_EMAIL_FLAGS
json.selected_email_flags @notification_setting.visible_selected_email_flags
json.all_push_flags NotificationSetting::VISIBLE_PUSH_FLAGS
json.selected_push_flags @notification_setting.visible_selected_push_flags
